import Provider from "./Provider";
import Header from "./Header";
import Footer from "./Footer";
import Main from "./Main";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata = {
  title: "tbaba.info",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className="font-sans">
      <body className="lg:container lg:mx-auto">
        <Provider>
          <Header />
          <Main>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </Main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
